In [6]:
import numpy as np

In [7]:
a = np.array([[1],
    [2],
    [3],
    [5]])

In [8]:
print(a)

[[1]
 [2]
 [3]
 [5]]


In [9]:
print(a+100)

[[101]
 [102]
 [103]
 [105]]


In [6]:
b = np.array([[1, 2, 3],
             [4, 5, 6]])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b + np.array([[100],
                   [200]]))

[[101 102 103]
 [204 205 206]]


In [11]:
c = np.array([[1, 2, 3],
             [4, 5, 6]])

In [12]:
print(c + 
      np.array([[100],
                 [200]]))

[[101 102 103]
 [204 205 206]]
