### Don't use Rank 1 Arrays

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
print(a)

[0.21629593 0.85569589 1.23957348 0.08191735 0.18394182]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[0.21629593 0.85569589 1.23957348 0.08191735 0.18394182]


In [6]:
print(np.dot(a,a))

2.356086852613757


In [7]:
print(np.dot(a,a.T))

2.356086852613757


In [8]:
a = np.random.randn(5,1)

In [9]:
print(a)

[[-1.31847351]
 [ 0.20976879]
 [ 2.05066553]
 [ 1.33832251]
 [-0.34280858]]


In [10]:
print(a.T)

[[-1.31847351  0.20976879  2.05066553  1.33832251 -0.34280858]]


In [11]:
print(np.dot(a,a.T))

[[ 1.73837239 -0.27657459 -2.70374818 -1.76454277  0.45198404]
 [-0.27657459  0.04400294  0.43016563  0.28073829 -0.07191054]
 [-2.70374818  0.43016563  4.20522913  2.74445184 -0.70298575]
 [-1.76454277  0.28073829  2.74445184  1.79110713 -0.45878844]
 [ 0.45198404 -0.07191054 -0.70298575 -0.45878844  0.11751773]]


In [12]:
print((a.T).T)

[[-1.31847351]
 [ 0.20976879]
 [ 2.05066553]
 [ 1.33832251]
 [-0.34280858]]
